artifacts_root : artifacts

data_ingestion :
  root_dir : artifacts/data_ingesition
  source_URL : https://github.com/XOGautham/Datasets/raw/main/TestSummarisation.zip
  local_data_file : artifacts/data_ingesition/data.zip
  unzip_dir : artifacts/data_ingesition