artifacts_root : artifacts

data_ingestion :
  root_dir : artifacts/data_ingesition
  source_URL : https://github.com/XOGautham/Datasets/raw/main/TestSummarisation.zip
  local_data_file : artifacts/data_ingesition/data.zip
  unzip_dir : artifacts/data_ingesition

data_validation :
  root_dir : artifacts/data_validation
  STATUS_FILE : artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES : ["train", "test", "validation", "dataset_dict.json"]

data_transformation:
  root_dir : artifacts/data_transformation
  data_path : artifacts/data_ingesition/samsum_dataset
  tokenizer_name : google/pegasus-cnn_dailymail
